### ISSUE TITLE
Re-order the actions in the example?

### ISSUE THREAD

**Issue by romilly** [skebir/rashell#1]
If you defined the directors before the movies, you wouldn't need to use force-insert.

Form a theoretical  and practical point of view I don't think one should encourage students to violate foreign key constraints.

**Comment by skebir** [comment]
I completely agree. Foreign key violation should be an exceptional case and should only be done if absolutely necessary (Case of two mutually referencing relations). I will change that in the documentation. Thanks for the suggestion.

**Comment by skebir** [comment]
I completely agree. Foreign key violation should be an exceptional case and should only be done if absolutely necessary (Case of two mutually referencing relations). I will change that in the documentation. Thanks for the suggestion.
